### ISSUE TITLE
Error with write function when element name has colon (:)

### ISSUE THREAD

**Issue by sbethea-cw** [cubewise-code/tm1py#720]
**Describe the bug**
When writing attribute cube values using cells.write() function for an element with a colon ':' in the element name, I receive message::
TM1py.Exceptions.Exceptions.TM1pyWriteFailureException: All 1 write operations failed. Details: ['TM1ProcessError_20220518180218_69674192_.log']
The log file appears as if TM1py parses the element name at the colon ':' and then does not recognize the shorter element name.
Original element name: 'Actual/Forecast FY17_LE1_2017-01-11 18:10'
Parsed element that TM1py tries to write to: 'Actual/Forecast FY17_LE1_2017-01-11 18'

**To Reproduce**
Use cells.write() function to write data to an element with a colon ':' in the element name.

**Expected behavior**
TM1py script should recognize the whole element name, regardless of special characters such as a colon ':'

**Version**
TM1py 1.9.1
TM1 Server Version: 11.8

**Additional context**

**Comment by MariusWirtz** [comment]
Hi @sbethea-cw,

strange. I can't reproduce the error. For me this executes fine:


``` python
from TM1py.Services.TM1Service import TM1Service

with TM1Service(
        base_url="https://localhost:12354",
        user="admin",
        password="apple") as tm1:

    cells = {
        ("Element with : character", "e1"): 22
    }

    tm1.cells.write("c1", cells, use_ti=True)
```


Can you upgrade to the current master branch and retry?


```
pip uninstall tm1py
pip install  https://github.com/cubewise-code/tm1py/archive/refs/heads/master.zip
```

**Comment by sbethea-cw** [comment]
Hello,

I upgraded to the latest master branch as you suggested and it did not seem to help.  I received the same error.

If it helps, below is the code I am running to sync attribute values.  Maybe it has something to do with the element_names_from_element_unique_names() function:

def sync_attrval(tm1_source, tm1_target, dim_src, dim_tgt):
    dim_src_exists = tm1_source.dimensions.exists(dim_src)
    dim_tgt_exists = tm1_target.dimensions.exists(dim_tgt)
    attr_dim_src_exists = tm1_source.dimensions.exists('}ElementAttributes_' + dim_src)
    attr_dim_tgt_exists = tm1_target.dimensions.exists('}ElementAttributes_' + dim_tgt)

    # Only continue with script if dimension exists on source server
    if not dim_src_exists:
        return

    # Only continue with script if dimension exists on target server
    if not dim_tgt_exists:
        return

    # Only continue with script if attribute dimension exists on source server
    if not attr_dim_src_exists:
        return

    # Only continue with script if attribute dimension exists on target server
    if not attr_dim_tgt_exists:
        return

    # Sync Dimension - Attribute Values
    # Query data from source TM1 model through MDX
    mdx = f"""
    SELECT
    NON EMPTY {{ TM1SUBSETALL( [{dim_src}] )}} on ROWS,
    NON EMPTY {{ TM1SUBSETALL( [}}ElementAttributes_{dim_src}] )}} on COLUMNS
    FROM [}}ElementAttributes_{dim_src}]
    """
    print(mdx)
    data = tm1_source.cubes.cells.execute_mdx(mdx, skip_rule_derived_cells=True, skip_zeros=True)

    # Get Element Names from Unique Element Names - source attribute values
    cells = {element_names_from_element_unique_names(coordinates): cell['Value']
             for coordinates, cell in
             data.items()}

    # Send data to target TM1 instance
    tm1_target.cells.write("}ElementAttributes_" + dim_tgt, cells, use_ti=True)


Thanks,

Shane


***@***.***<https://cubewise.com/about-us/>
Shane Bethea | Senior Consultant
Cubewise | US Central
m. +1 404 580 7878 | t. +1 857 208 7267
#DoGoodTM1 | ***@***.******@***.***>

**Comment by MariusWirtz** [comment]
Hi,

I created a fix for the issue.
If you are explicit about the hierarchy it should work now.

``` python

from TM1py.Services.TM1Service import TM1Service

with TM1Service(
        base_url="https://localhost:12354",
        user="admin",
        password="apple") as tm1:

    cells = {
        ("d1:e1", "Number2"): 11,
        ("d1:Element with : character", "Number2"): 22
    }

    tidy_cells = dict()
    cells_with_colon_in_elements = dict()

    tm1.cells.write("}ElementAttributes_d1", cells, use_ti=True)

```

Please upgrade to the hotfix branch: `https://github.com/cubewise-code/tm1py/archive/refs/heads/issue/colon-in-element-names-breaks-attribute-write.zip`:

```
pip uninstall tm1py
pip install https://github.com/cubewise-code/tm1py/archive/refs/heads/issue/colon-in-element-names-breaks-attribute-write.zip
```

**Comment by MariusWirtz** [comment]
In your case, assuming that alternate hierarchies are not used, you can alter the code to make the tuples hierarchy explicit like this:

``` python
from TM1py.Services.TM1Service import TM1Service

dim = "d1"

with TM1Service(
        base_url="https://localhost:12354",
        user="admin",
        password="apple") as tm1:
    mdx = f"""
    SELECT
    NON EMPTY {{ TM1SUBSETALL( [{dim}] )}} on ROWS,
    NON EMPTY {{ TM1SUBSETALL( [}}ElementAttributes_{dim}] )}} on COLUMNS
    FROM [}}ElementAttributes_{dim}]
    """

    cells = tm1.cubes.cells.execute_mdx(mdx, skip_rule_derived_cells=True, skip_zeros=True, element_unique_names=False,
                                        skip_cell_properties=True)

    #
    cells = {(f"{dim}:{elements[0]}", elements[1]): value for elements, value in cells.items()}
    print(cells)
    # Send data to target TM1 instance
    tm1.cells.write("}ElementAttributes_" + dim, cells, use_ti=True)
```

**Comment by japwah** [comment]
Hi @MariusWirtz ,

Shane and I were testing the hotfix for the issue we are seeing and the issue still persists:

Error message in python:
raise TM1pyWriteFailureException(statuses, log_files)
TM1py.Exceptions.Exceptions.TM1pyWriteFailureException: All 1 write operations failed. Details: ['TM1ProcessError_20220610175006_99826100_.log']

This is the contents of the process error log above:
![image](https://user-images.githubusercontent.com/54960768/173123865-88f48376-e7d6-4369-b876-e801c6a9d334.png)

This is a screenshot of the dimension in question. Attributes were not synced:
![image](https://user-images.githubusercontent.com/54960768/173124142-1fa9e483-b295-4bec-a680-816bbfdba55e.png)

This is the code that is being used. The code that has been updated is in the "def sync_attrval" function, where element_unique_names=False now:



`##############################################################################################################
### TM1 DIM SYNC -
### Use this script to synchronize dimensions between between the same or different  TM1 servers
### This script does the following:
###    - uses passed in source/target dimension names to synchronize dimensions between two servers
###    - dims can be on the same or different TM1 servers
###    - dims can have the same or different names
###    - script will sync subsets and attribute values based on parameter value
###
##############################################################################################################
### CHANGE HISTORY:
### MODIFICATION DATE   CHANGED BY      COMMENT
### 2022-04-28		    Shane Bethea	Initial Creation
###
##############################################################################################################

import configparser
import sys
import os
import logging
from TM1py import TM1Service
from TM1py.Utils import element_names_from_element_unique_names
from datetime import datetime

#Parameters
LOG_FILE        = "Dim_Sync_Between_Servers.log"
currentDay      = datetime.now().strftime('%d')
currentMonth    = datetime.now().strftime('%m')
currentYear     = datetime.now().year


def configure_logging():
    if log_dir == '':
        log_file = os.path.join(wd,LOG_FILE)
    else:
        log_file = os.path.join(log_dir,LOG_FILE)

    logging.basicConfig(
        filename=str(log_file),
        format="%(asctime)s - %(levelname)s - %(message)s",
        level=logging.INFO,
    )
    # also log to stdout
    logging.getLogger().addHandler(logging.StreamHandler(sys.stdout))


def result_logging(filename, result):
    if log_dir == '':
        result_file = os.path.join(wd,filename + "_" + result + ".txt")
        if os.path.exists(os.path.join(wd,filename + "_Success.txt")):
            os.remove(os.path.join(wd,filename + "_Success.txt"))
        if os.path.exists(os.path.join(wd,filename + "_Error.txt")):
            os.remove(os.path.join(wd,filename + "_Error.txt"))
    else:
        result_file = os.path.join(log_dir,filename + "_" + result + ".txt")
        if os.path.exists(os.path.join(log_dir,filename + "_Success.txt")):
            os.remove(os.path.join(log_dir,filename + "_Success.txt"))
        if os.path.exists(os.path.join(log_dir,filename + "_Error.txt")):
            os.remove(os.path.join(log_dir,filename + "_Error.txt"))

    with open(result_file, "w") as file:
        file.write(result)


def cube_logging_off(tm1, cube):
    # Turn Off Cube Logging
    cube_properties = "}CubeProperties"
    cube_logging = {(cube, 'LOGGING'): "NO"}
    tm1.cells.write(cube_properties, cube_logging, use_ti=True)


def clear(tm1, dimension):
    cub_exists = tm1.cubes.exists("}ElementAttributes_" + dimension)

    # Only continue with script if cube exists on server
    if not cub_exists:
        return

    # Query data from source TM1 model through MDX
    view_mdx = f"""
    SELECT
    NON EMPTY {{ TM1SUBSETALL( [{dimension}] )}} on ROWS,
    NON EMPTY {{ TM1SUBSETALL( [}}ElementAttributes_{dimension}] )}} on COLUMNS
    FROM [}}ElementAttributes_{dimension}]
    """

    # Clear data from TM1 cube defined by MDX
    # Function clear_with_mdx requires TM1 version 11.7 and higher
    if num_srv_version >= 11.7:
        # Server version is greater than or equal to 11.7
        logging.info(f"Clearing data in }}ElementAttributes_{dimension} via MDX.")
        tm1.cells.clear_with_mdx(cube="}ElementAttributes_" + dimension, mdx=view_mdx)
    else:
        # Server version is less than 11.7
        # Query data from target TM1 model through MDX
        data = tm1.cubes.cells.execute_mdx(mdx=view_mdx, skip_consolidated_cells=1, skip_rule_derived_cells=1, skip_zeros=1)

        # Get Element Names from Unique Element Names - target data values
        cells = {}
        start = datetime.now()
        for coordinates, cell in data.items():
            if type(cell['Value']) == str:
                cells[element_names_from_element_unique_names(coordinates)] = ''
            else:
                cells[element_names_from_element_unique_names(coordinates)] = 0

        logging.info(f"Clearing data in }}ElementAttributes_{dimension}.")
        # Send zero'd out data to target TM1 instance
        tm1.cells.write("}ElementAttributes_" + dimension, cells, use_ti=True)
        logging.info(f"Clearing data elapsed time: " + str(datetime.now() - start))


def sync_attrval(tm1_source, tm1_target, dim_src, dim_tgt):
    dim_src_exists = tm1_source.dimensions.exists(dim_src)
    dim_tgt_exists = tm1_target.dimensions.exists(dim_tgt)
    attr_dim_src_exists = tm1_source.dimensions.exists('}ElementAttributes_' + dim_src)
    attr_dim_tgt_exists = tm1_target.dimensions.exists('}ElementAttributes_' + dim_tgt)

    # Only continue with script if dimension exists on source server
    if not dim_src_exists:
        return

    # Only continue with script if dimension exists on target server
    if not dim_tgt_exists:
        return

    # Only continue with script if attribute dimension exists on source server
    if not attr_dim_src_exists:
        return

    # Only continue with script if attribute dimension exists on target server
    if not attr_dim_tgt_exists:
        return

    # Sync Dimension - Attribute Values
    # Query data from source TM1 model through MDX
    mdx = f"""
    SELECT
    NON EMPTY {{ TM1SUBSETALL( [{dim_src}] )}} on ROWS,
    NON EMPTY {{ TM1SUBSETALL( [}}ElementAttributes_{dim_src}] )}} on COLUMNS
    FROM [}}ElementAttributes_{dim_src}]
    """
    print(mdx)
    **data = tm1_source.cubes.cells.execute_mdx(mdx, skip_rule_derived_cells=True, skip_zeros=True, element_unique_names=False)**

    # Get Element Names from Unique Element Names - source attribute values
    #cells = {element_names_from_element_unique_names(coordinates): cell['Value']
    #         for coordinates, cell in
    #         data.items()}
    cells = data
    # Send data to target TM1 instance
    tm1_target.cells.write("}ElementAttributes_" + dim_tgt, cells, use_ti=True)


def replicate_dimension(tm1_source, tm1_target, dim_src, dim_tgt):
    dimension_master = tm1_source.dimensions.get(dimension_name=dim_src)

    if dim_src != dim_tgt:
        dimension_master.name = dim_tgt

    logging.info(f'Checking dimension {dim_tgt}')
    if not tm1_target.dimensions.exists(dim_tgt):
        logging.info(f'\tDimension missing. Creating Dimension: {dim_tgt}')
        tm1_target.dimensions.create(dimension_master)

    dimension_other = tm1_target.dimensions.get(dimension_name=dim_tgt)

    if dimension_master != dimension_other:
        logging.info(f'Recognized changes. Updating dimension: {dimension_master.name}')
        tm1_target.dimensions.update(dimension_master)

    if update_subsets == '1':
        subsets_names = tm1_source.subsets.get_all_names(dim_src)
        for subsets_name in subsets_names:
            subset_master = tm1_source.subsets.get(subsets_name, dimension_name=dim_src)

            if dim_src != dim_tgt:
                subset_master.hierarchy_name = dim_tgt
                subset_master.dimension_name = dim_tgt
                if subset_master.expression != None:
                    subset_master.expression = subset_master.expression.replace(dim_src, dim_tgt)

            if not tm1_target.subsets.exists(subsets_name, dimension_name=dim_tgt):
                logging.info(f"\tSubset missing. Creating Subset: '{subsets_name}'")
                tm1_target.subsets.create(subset_master)
            else:
                subset_other = tm1_target.subsets.get(subsets_name, dimension_name=dim_tgt)
                if subset_master != subset_other:
                    logging.info(f"\tRecognized changes. Updating Subset: '{subsets_name}'")
                    tm1_target.subsets.update(subset_master)


if __name__ == '__main__':
    try:
        #logging.info(f"Starting script '{__file__}'")

        instance_src    = sys.argv[1]   # ex. tm1prem
        instance_tgt    = sys.argv[2]   # ex. tm1cloud
        dim_name_src    = sys.argv[3]   # ex. D365 Company
        dim_name_tgt    = sys.argv[4]   # ex. D365 Digital Company
        update_subsets  = sys.argv[5]   # ex. "1" to sync subsets or "0" to not sync subsets
        update_attr     = sys.argv[6]   # ex. "1" to sync attribute values or "0" to not sync attribute values
        cfg = sys.argv[7]               # ex. "config.ini"
        log_dir = sys.argv[8]           # ex. "C:/Python/Scripts/"

        try:
            wd = sys._MEIPASS
        except AttributeError:
            wd = os.getcwd()

        result_file = instance_src + "_" + dim_name_src + "_to_" + instance_tgt + "_" + dim_name_tgt

        configure_logging()
        cfg_file_path = os.path.join(wd,cfg)

        config = configparser.ConfigParser()
        config.read(cfg_file_path)

        if dim_name_tgt == "":
            dim_name_tgt = dim_name_src

        with TM1Service(**config[instance_src]) as tm1_src:

            logging.info(f"Connection to Source server ({instance_src}) completed.")

            with TM1Service(**config[instance_tgt]) as tm1_tgt:

                logging.info(f"Connection to Target server ({instance_tgt}) completed.")
                tgt_srv_version = tm1_tgt.server.get_product_version()
                logging.info(f"Target TM1 version is {tgt_srv_version}.")
                num_srv_version = float(tgt_srv_version[0:4])

                if config.has_option(instance_src, "address"):
                    address_src = config[instance_src]["address"]
                else:
                    address_src = config[instance_src]["base_url"]

                if config.has_option(instance_tgt, "address"):
                    address_tgt = config[instance_tgt]["address"]
                else:
                    address_tgt = config[instance_tgt]["base_url"]

                logging.info(f'{address_src} --> {address_tgt}')
                if dim_name_src == dim_name_tgt:
                    logging.info(f"Pushing '{dim_name_src}' dimension to '{instance_tgt}' server.")
                else:
                    logging.info(f"Pushing '{dim_name_src}' dimension as '{dim_name_tgt}' to '{instance_tgt}' server.")

                # Synchronize dimension on target server from source server
                replicate_dimension(tm1_src, tm1_tgt, dim_name_src, dim_name_tgt)

                if update_attr == '1':
                    attr_cub_exists = tm1_tgt.cubes.exists("}ElementAttributes_" + dim_name_tgt)

                    # Only continue with attribute update if attribute cube exists on target server
                    if attr_cub_exists:
                        # Turn Off Cube Logging - Assume No Logging for Element Attributes Cubes
                        logging.info('Turning off Element Attributes cube logging.')
                        cube_logging_off(tm1_tgt, "}ElementAttributes_" + dim_name_tgt)

                        # Zero out target Element Attributes cube
                        logging.info('Clearing out target Element Attributes cube.')
                        clear(tm1_tgt, dim_name_tgt)

                        # Synchronize attribute values on target server from source server
                        logging.info('Synchronizing attribute values on target server from source server.')
                        sync_attrval(tm1_src, tm1_tgt, dim_name_src, dim_name_tgt)

                result_logging(result_file, "Success")
                logging.info('Replication completed.')
                logging.info(" ")

    except:
        result_logging(result_file, "Error")
        logging.exception("Unexpected Error")
        logging.info(" ")
`

**Comment by MariusWirtz** [comment]
Hi @japwah,

make sure to explicitly add the (default) dimension before the elementname like this. Then it should work:

```python
    cells = tm1.cubes.cells.execute_mdx(mdx, skip_rule_derived_cells=True, skip_zeros=True, element_unique_names=False,
                                        skip_cell_properties=True)

    
    cells = {(f"{dim}:{elements[0]}", elements[1]): value for elements, value in cells.items()}
```

**Comment by sbethea-cw** [comment]
Hi @MariusWirtz,

That fixed our issue.  Thanks!
